# Generated by Django 4.1 on 2022-12-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_userfollowing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boyut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boyut', models.CharField(max_length=200)),
            ],
        ),
    ]
