# Generated by Django 4.1 on 2022-12-12 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_boyut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='boyut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.boyut'),
        ),
    ]
