# Generated by Django 4.1 on 2022-12-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ilan_boyut'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ilan adı'),
        ),
        migrations.AlterField(
            model_name='ilan',
            name='price',
            field=models.IntegerField(verbose_name='Fiyat'),
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
