# Generated by Django 4.1 on 2022-12-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_phone_no_alter_ilan_name_alter_ilan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
