# Generated by Django 4.1 on 2022-12-22 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_kaydet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
