# Generated by Django 4.1 on 2022-12-23 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tip'),
        ),
    ]
