# Generated by Django 4.1 on 2022-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_ilan_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='metrekare',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
