# Generated by Django 4.1 on 2022-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_ilan_metrekare'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
