# Generated by Django 4.1 on 2023-01-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_ilan_image4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilan_id', models.CharField(blank=True, max_length=200, null=True)),
                ('eski_fiyat', models.CharField(blank=True, max_length=200, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
